global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]
  - job_name: "api-gateway"
    static_configs:
      - targets: ["api-gateway:3000"]
  - job_name: "auth-service"
    static_configs:
      - targets: ["auth-service:3001"]
  - job_name: "profile-service"
    static_configs:
      - targets: ["profile-service:3002"]
  - job_name: "jobs-service"
    static_configs:
      - targets: ["jobs-service:3003"]
  - job_name: "notifications-service"
    static_configs:
      - targets: ["notifications-service:3004"]
  - job_name: "admin-service"
    static_configs:
      - targets: ["admin-service:3005"]
  - job_name: "ai-matching-service"
    static_configs:
      - targets: ["ai-matching-service:3006"]
